### ISSUE TITLE
resolves to an APK archive which is not supported as a compilation dependency

### ISSUE THREAD

**Issue by lclc** [alahammad/ShowEdittextPassword#1]
Hi,

I'm want to use ShowEdittextPassword, but gradle complains because it gets an APK.

Do you have an idea why adding 
compile 'com.github.alahammad:ShowEdittextPassword:1882cf05cf'
to build.gradle doesn't work? 
I already had the url "https://jitpack.io" in there.

I always get a "Dependency com.github.alahammad:ShowEdittextPassword:1882cf05cf on project XYZ resolves to an APK archive which is not supported as a compilation dependency. " error. Any ideas?

**Comment by alahammad** [comment]
Hi,

updated !! please check
